<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nitsan_sharethis"
 *
 * Auto generated by Extension Builder 2016-09-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '[NITSAN] Plugin for www.Sharethis.com',
	'description' => 'One of the only TYPO3 extension is developed to integrate all the features of www.Sharethis.com which is one of the most popular third-party social media platform!',
	'category' => 'plugin',
	'author' => 'NITSAN Technologies',
	'author_email' => 'sanjay@nitsan.in',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-8.9.9',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
